apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    hub.jupyter.org/username: {{ .Values.unescaped_username | quote }}
    kubetemplatespawner/delete: user
  labels:
    app.kubernetes.io/component: singleuser-storage
    # app.kubernetes.io/instance: jupyterhub
    app.kubernetes.io/managed-by: kubetemplatespawner
    # app.kubernetes.io/name: jupyterhub
    hub.jupyter.org/username: "{{ .Values.escaped_username }}"
  # Use escaped_username to share a volume across all user's servers
  name: jupyter-{{ .Values.escaped_user_server }}
  # namespace: 
spec:
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
