{{ if .Values.serviceEnabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    hub.jupyter.org/username: {{ .Values.unescaped_username | quote }}
    kubetemplatespawner/connection: "true"
    kubetemplatespawner/delete: server
  labels:
    # app.kubernetes.io/instance: jupyterhub
    # app.kubernetes.io/name: jupyterhub
    app.kubernetes.io/component: singleuser-server
    app.kubernetes.io/managed-by: kubetemplatespawner
    hub.jupyter.org/servername: "{{ .Values.escaped_servername }}"
    hub.jupyter.org/username: "{{ .Values.escaped_username }}"
  name: jupyter-{{ .Values.escaped_user_server }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      target_port: {{ .Values.port }}
  selector:
    app.kubernetes.io/component: singleuser-server
    hub.jupyter.org/servername: "{{ .Values.escaped_servername }}"
    hub.jupyter.org/username: "{{ .Values.escaped_username }}"
{{ end }}
