hub:
  image:
    name: ghcr.io/manics/jupyterhub-kubetemplatespawner
    tag: main
    pullPolicy: Always

  config:
    JupyterHub:
      spawner_class: kubetemplate
    KubeTemplateSpawner:
      template_path: /src/kubetemplatespawner/example/
      extra_vars:
        serviceEnabled: true

singleuser:
  storage:
    # Everything is done in kubetemplatespawner
    type: none

proxy:
  service:
    type: ClusterIP

ingress:
  enabled: true
  hosts:
    - example.127.0.0.1.nip.io

scheduling:
  userScheduler:
    enabled: false
  userPlaceholder:
    enabled: false

debug:
  enabled: true
