# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Build
on:
  - push
  - pull_request

env:
  REGISTRY: ghcr.io
  OWNER_IMAGE: ${{ github.repository }}
  # Set to "" to publish container on tags only
  # Set to "<branch-name>" to also publish on every push to <branch-name>
  PUBLISH_BRANCH: "main"
  DEV_BRANCH: "dev"
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      # https://github.com/pre-commit/action
      - uses: pre-commit/action@v3.0.1

  test:
    name: Test
    strategy:
      # Keep running so we can see if other tests pass
      fail-fast: false
      matrix:
        k3s:
          - v1.32

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: "*-requirements.txt"

      - uses: actions/setup-node@v4

      - name: Setup self-signed CA
        run: |
          ./ci/self-signed-ca.sh

      # TODO: use https://github.com/jupyterhub/action-k3s-helm/pull/122/ if it's merged
      - uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: ${{ matrix.k3s }}
          metrics-enabled: false

      - name: Setup local registry
        run: |
          kubectl create ns registry
          kubectl create secret tls registry-cert \
            -n registry \
            --cert=certs/registry.crt \
            --key=certs/registry.key
          kubectl apply -f ./ci/registry.yaml -n registry
          kubectl rollout status --watch --timeout=5m deployment/registry -n registry

      - name: Registry address
        id: registry
        run: |
          echo "registry-host=$CERTIFICATE_IP:5000" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          python -m pip install -r dev-requirements.txt
          npm install -g configurable-http-proxy

      - name: Run tests
        run: python -mpytest -v -m "not z2jh"

      - name: Build image
        run: |
          docker build -t ${{ steps.registry.outputs.registry-host }}/kubetemplatespawner .
          docker push ${{ steps.registry.outputs.registry-host }}/kubetemplatespawner

      - name: Set k8s ingress address
        run: |
          # Needs to resolve inside and outside the cluster
          K8S_HOSTNAME=$(hostname -I | awk '{print $1}').nip.io
          echo "K8S_HOSTNAME=$K8S_HOSTNAME" >> $GITHUB_ENV

      - name: Deploy Z2JH
        run: |
          yq -i -e '(.hub.image.name="${{ steps.registry.outputs.registry-host }}/kubetemplatespawner") | (.hub.image.tag="latest")' config.yaml
          git diff

          kubectl create namespace dev
          ../ci/run_codeblocks.py README.md --sub "<k8s-hostname>=$K8S_HOSTNAME" --run

          kubectl -n dev describe deploy/hub
        working-directory: ./z2jh

      - name: Test Z2JH
        run: |
          python -mpytest -v -m z2jh --jupyterhub-host="http://$K8S_HOSTNAME"

      - name: Kubernetes namespace report
        uses: jupyterhub/action-k8s-namespace-report@v1
        if: always()
        with:
          important-workloads: deploy/hub deploy/proxy
          namespace: dev

  container:
    name: Container
    runs-on: ubuntu-24.04
    needs:
      - lint
      - test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          images: ${{ env.REGISTRY }}/${{ env.OWNER_IMAGE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Should container be pushed
        run: |
          PUSH="${{ github.event_name == 'push' &&
            (
              github.ref == format('refs/heads/{0}', env.PUBLISH_BRANCH) ||
              github.ref == format('refs/heads/{0}', env.DEV_BRANCH) ||
              startsWith(github.ref, 'refs/tags/')
            )
          }}"
          echo PUSH="$PUSH" >> $GITHUB_ENV

      - name: Login to container registry
        uses: docker/login-action@v3
        if: ${{ env.PUSH == 'true' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to container registry
        uses: docker/build-push-action@v6
        with:
          # Needed so that .git directory is available to embed version info
          context: .
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ env.PUSH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  publish-pypi:
    name: Pypi
    if: startsWith(github.ref, 'refs/tags')
    needs:
      # Only publish if other jobs passed
      - lint
      - test
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/kubetemplatespawner
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Build package
        run: |
          python -mpip install build
          python -mbuild

      - name: Publish to PyPI (trusted publisher)
        uses: pypa/gh-action-pypi-publish@v1.13.0
