# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Build
on:
  - push
  - pull_request

env:
  REGISTRY: ghcr.io
  OWNER_IMAGE: ${{ github.repository }}
  # Set to "" to publish container on tags only
  # Set to "<branch-name>" to also publish on every push to <branch-name>
  PUBLISH_BRANCH: "main"
  DEV_BRANCH: "dev"
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      # https://github.com/pre-commit/action
      - uses: pre-commit/action@v3.0.1

  test:
    name: Test
    strategy:
      # Keep running so we can see if other tests pass
      fail-fast: false
      matrix:
        test:
          - a
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: "*-requirements.txt"

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          python -m pip install -r dev-requirements.txt
          npm install -g configurable-http-proxy

      # - name: Update setuptools_scm version
      #   run: python setup.py build

      # - name: Run tests
      #   run: pytest --cov=kubetemplatespawner tests -v --cov-report=xml --cov-report=term-missing --cov-fail-under=95

  container:
    name: Container
    runs-on: ubuntu-24.04
    needs:
      - lint
      - test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          images: ${{ env.REGISTRY }}/${{ env.OWNER_IMAGE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Should container be pushed
        run: |
          PUSH="${{ github.event_name == 'push' &&
            (
              github.ref == format('refs/heads/{0}', env.PUBLISH_BRANCH) ||
              github.ref == format('refs/heads/{0}', env.DEV_BRANCH) ||
              startsWith(github.ref, 'refs/tags/')
            )
          }}"
          echo PUSH="$PUSH" >> $GITHUB_ENV

      - name: Login to container registry
        uses: docker/login-action@v3
        if: ${{ env.PUSH == 'true' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to container registry
        uses: docker/build-push-action@v6
        with:
          # Needed so that .git directory is available to embed version info
          context: .
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ env.PUSH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  publish-pypi:
    name: Pypi
    if: startsWith(github.ref, 'refs/tags')
    needs:
      # Only publish if other jobs passed
      - lint
      - test
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/kubetemplatespawner
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Build package
        run: |
          python -mpip install wheel
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI (trusted publisher)
        uses: pypa/gh-action-pypi-publish@v1.12.4
